name: AndroidBuild
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
    build:
      runs-on:
        macos-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.7

        - name: Setup Java JDK 1.8
          uses: actions/setup-java@v4.2.1
          with:
            distribution: 'adopt'
            java-version: '1.8'
            java-package: jdk
            check-latest: false
            server-id: github
            server-username: ${{ secrets.GITHUB_ACTOR }}
            server-password: ${{ secrets.GITHUB_TOKEN }}
            overwrite-settings: true

        - name: Build with Gradle
          uses: ./gradlew build

        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.3.3
          with:
            name: AndroidCICD.apk
            path: app/build/outputs/apk/app-debug.apk
